package nl.rumfumme.gl.enums;

import java.util.HashMap;
import java.util.Map;

import com.badlogic.gdx.graphics.GL32;

public enum ProgramParameter {
    ACTIVE_ATOMIC_COUNTER_BUFFERS(GL32.GL_ACTIVE_ATOMIC_COUNTER_BUFFERS),
    ACTIVE_ATTRIBUTES(GL32.GL_ACTIVE_ATTRIBUTES),
    ACTIVE_ATTRIBUTE_MAX_LENGTH(GL32.GL_ACTIVE_ATTRIBUTE_MAX_LENGTH),
    ACTIVE_UNIFORMS(GL32.GL_ACTIVE_UNIFORMS),
    ACTIVE_UNIFORM_BLOCKS(GL32.GL_ACTIVE_UNIFORM_BLOCKS),
    ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH(GL32.GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH),
    ACTIVE_UNIFORM_MAX_LENGTH(GL32.GL_ACTIVE_UNIFORM_MAX_LENGTH),
    ATTACHED_SHADERS(GL32.GL_ATTACHED_SHADERS),
    COMPUTE_WORK_GROUP_SIZE(GL32.GL_COMPUTE_WORK_GROUP_SIZE),
    DELETE_STATUS(GL32.GL_DELETE_STATUS),
    INFO_LOG_LENGTH(GL32.GL_INFO_LOG_LENGTH),
    LINK_STATUS(GL32.GL_LINK_STATUS),
    PROGRAM_BINARY_RETRIEVABLE_HINT(GL32.GL_PROGRAM_BINARY_RETRIEVABLE_HINT),
    PROGRAM_SEPARABLE(GL32.GL_PROGRAM_SEPARABLE),
    TRANSFORM_FEEDBACK_BUFFER_MODE(GL32.GL_TRANSFORM_FEEDBACK_BUFFER_MODE),
    TRANSFORM_FEEDBACK_VARYINGS(GL32.GL_TRANSFORM_FEEDBACK_VARYINGS),
    TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH(GL32.GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH),
    VALIDATE_STATUS(GL32.GL_VALIDATE_STATUS);

    public int GL;
    private static Map<Integer, ProgramParameter> glMap = new HashMap<Integer, ProgramParameter>();
    
    static {
        for(ProgramParameter t : ProgramParameter.values()) {
            glMap.put(t.GL, t);
        }
    }

    private ProgramParameter(int GL) {
        this.GL = GL;
    }

    public static ProgramParameter valueOf(int GL) {
        return glMap.get(GL);
    }
}
