package nl.rumfumme.gl.enums;

import java.util.HashMap;
import java.util.Map;

import com.badlogic.gdx.graphics.GL32;

public enum StateParameter {
    ACTIVE_TEXTURE(GL32.GL_ACTIVE_TEXTURE, Integer.class),
    ALIASED_LINE_WIDTH_RANGE(GL32.GL_ALIASED_LINE_WIDTH_RANGE),
    ALIASED_POINT_SIZE_RANGE(GL32.GL_ALIASED_POINT_SIZE_RANGE),
    ALPHA_BITS(GL32.GL_ALPHA_BITS, Integer.class),
    ARRAY_BUFFER_BINDING(GL32.GL_ARRAY_BUFFER_BINDING, Integer.class),
    BLEND(GL32.GL_BLEND, Boolean.class),
    BLEND_COLOR(GL32.GL_BLEND_COLOR, 4, Float.class),
    BLEND_DST_ALPHA(GL32.GL_BLEND_DST_ALPHA),
    BLEND_DST_RGB(GL32.GL_BLEND_DST_RGB),
    BLEND_EQUATION_ALPHA(GL32.GL_BLEND_EQUATION_ALPHA),
    BLEND_EQUATION_RGB(GL32.GL_BLEND_EQUATION_RGB),
    BLEND_SRC_ALPHA(GL32.GL_BLEND_SRC_ALPHA),
    BLEND_SRC_RGB(GL32.GL_BLEND_SRC_RGB),
    BLUE_BITS(GL32.GL_BLUE_BITS),
    COLOR_CLEAR_VALUE(GL32.GL_COLOR_CLEAR_VALUE, 4, Float.class),
    COLOR_WRITEMASK(GL32.GL_COLOR_WRITEMASK, 4, Boolean.class),
    COMPRESSED_TEXTURE_FORMATS(GL32.GL_COMPRESSED_TEXTURE_FORMATS),
    COPY_READ_BUFFER_BINDING(GL32.GL_COPY_READ_BUFFER_BINDING),
    COPY_WRITE_BUFFER_BINDING(GL32.GL_COPY_WRITE_BUFFER_BINDING),
    CULL_FACE(GL32.GL_CULL_FACE, Boolean.class),
    CULL_FACE_MODE(GL32.GL_CULL_FACE_MODE),
    CURRENT_PROGRAM(GL32.GL_CURRENT_PROGRAM),
    DEPTH_BITS(GL32.GL_DEPTH_BITS),
    DEPTH_CLEAR_VALUE(GL32.GL_DEPTH_CLEAR_VALUE),
    DEPTH_FUNC(GL32.GL_DEPTH_FUNC),
    DEPTH_RANGE(GL32.GL_DEPTH_RANGE, 2),
    DEPTH_TEST(GL32.GL_DEPTH_TEST, Boolean.class),
    DEPTH_WRITEMASK(GL32.GL_DEPTH_WRITEMASK, Boolean.class),
    DISPATCH_INDIRECT_BUFFER_BINDING(GL32.GL_DISPATCH_INDIRECT_BUFFER_BINDING),
    DITHER(GL32.GL_DITHER, Boolean.class),
    DRAW_BUFFER0(GL32.GL_DRAW_BUFFER0),
    DRAW_BUFFER1(GL32.GL_DRAW_BUFFER1),
    DRAW_BUFFER2(GL32.GL_DRAW_BUFFER2),
    DRAW_BUFFER3(GL32.GL_DRAW_BUFFER3),
    DRAW_BUFFER4(GL32.GL_DRAW_BUFFER4),
    DRAW_BUFFER5(GL32.GL_DRAW_BUFFER5),
    DRAW_BUFFER6(GL32.GL_DRAW_BUFFER6),
    DRAW_BUFFER7(GL32.GL_DRAW_BUFFER7),
    DRAW_BUFFER8(GL32.GL_DRAW_BUFFER8),
    DRAW_BUFFER9(GL32.GL_DRAW_BUFFER9),
    DRAW_BUFFER10(GL32.GL_DRAW_BUFFER10),
    DRAW_BUFFER11(GL32.GL_DRAW_BUFFER11),
    DRAW_BUFFER12(GL32.GL_DRAW_BUFFER12),
    DRAW_BUFFER13(GL32.GL_DRAW_BUFFER13),
    DRAW_BUFFER14(GL32.GL_DRAW_BUFFER14),
    DRAW_BUFFER15(GL32.GL_DRAW_BUFFER15),
    DRAW_FRAMEBUFFER_BINDING(GL32.GL_DRAW_FRAMEBUFFER_BINDING),
    ELEMENT_ARRAY_BUFFER_BINDING(GL32.GL_ELEMENT_ARRAY_BUFFER_BINDING),
    FRAGMENT_SHADER_DERIVATIVE_HINT(GL32.GL_FRAGMENT_SHADER_DERIVATIVE_HINT),
    FRONT_FACE(GL32.GL_FRONT_FACE),
    GENERATE_MIPMAP_HINT(GL32.GL_GENERATE_MIPMAP_HINT),
    GREEN_BITS(GL32.GL_GREEN_BITS),
    IMAGE_BINDING_LAYERED(GL32.GL_IMAGE_BINDING_LAYERED),
    IMPLEMENTATION_COLOR_READ_FORMAT(GL32.GL_IMPLEMENTATION_COLOR_READ_FORMAT),
    IMPLEMENTATION_COLOR_READ_TYPE(GL32.GL_IMPLEMENTATION_COLOR_READ_TYPE),
    LINE_WIDTH(GL32.GL_LINE_WIDTH),
    MAJOR_VERSION(GL32.GL_MAJOR_VERSION),
    MAX_3D_TEXTURE_SIZE(GL32.GL_MAX_3D_TEXTURE_SIZE),
    MAX_ARRAY_TEXTURE_LAYERS(GL32.GL_MAX_ARRAY_TEXTURE_LAYERS),
    MAX_ATOMIC_COUNTER_BUFFER_BINDINGS(GL32.GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS),
    MAX_COLOR_ATTACHMENTS(GL32.GL_MAX_COLOR_ATTACHMENTS),
    MAX_COLOR_TEXTURE_SAMPLES(GL32.GL_MAX_COLOR_TEXTURE_SAMPLES),
    MAX_COMBINED_ATOMIC_COUNTERS(GL32.GL_MAX_COMBINED_ATOMIC_COUNTERS),
    MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS(GL32.GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS),
    MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS(GL32.GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS),
    MAX_COMBINED_SHADER_STORAGE_BLOCKS(GL32.GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS),
    MAX_COMBINED_TEXTURE_IMAGE_UNITS(GL32.GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS),
    MAX_COMBINED_UNIFORM_BLOCKS(GL32.GL_MAX_COMBINED_UNIFORM_BLOCKS),
    MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS(GL32.GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS),
    MAX_COMPUTE_ATOMIC_COUNTERS(GL32.GL_MAX_COMPUTE_ATOMIC_COUNTERS),
    MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS(GL32.GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS),
    MAX_COMPUTE_SHADER_STORAGE_BLOCKS(GL32.GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS),
    MAX_COMPUTE_TEXTURE_IMAGE_UNITS(GL32.GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS),
    MAX_COMPUTE_UNIFORM_BLOCKS(GL32.GL_MAX_COMPUTE_UNIFORM_BLOCKS),
    MAX_COMPUTE_UNIFORM_COMPONENTS(GL32.GL_MAX_COMPUTE_UNIFORM_COMPONENTS),
    MAX_COMPUTE_WORK_GROUP_INVOCATIONS(GL32.GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS),
    MAX_COMPUTE_WORK_GROUP_COUNT(GL32.GL_MAX_COMPUTE_WORK_GROUP_COUNT),
    MAX_COMPUTE_WORK_GROUP_SIZE(GL32.GL_MAX_COMPUTE_WORK_GROUP_SIZE),
    MAX_CUBE_MAP_TEXTURE_SIZE(GL32.GL_MAX_CUBE_MAP_TEXTURE_SIZE),
    MAX_DRAW_BUFFERS(GL32.GL_MAX_DRAW_BUFFERS),
    MAX_ELEMENT_INDEX(GL32.GL_MAX_ELEMENT_INDEX),
    MAX_ELEMENTS_INDICES(GL32.GL_MAX_ELEMENTS_INDICES),
    MAX_ELEMENTS_VERTICES(GL32.GL_MAX_ELEMENTS_VERTICES),
    MAX_FRAGMENT_ATOMIC_COUNTERS(GL32.GL_MAX_FRAGMENT_ATOMIC_COUNTERS),
    MAX_FRAGMENT_INPUT_COMPONENTS(GL32.GL_MAX_FRAGMENT_INPUT_COMPONENTS),
    MAX_FRAGMENT_SHADER_STORAGE_BLOCKS(GL32.GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS),
    MAX_FRAGMENT_UNIFORM_BLOCKS(GL32.GL_MAX_FRAGMENT_UNIFORM_BLOCKS),
    MAX_FRAGMENT_UNIFORM_COMPONENTS(GL32.GL_MAX_FRAGMENT_UNIFORM_COMPONENTS),
    MAX_FRAGMENT_UNIFORM_VECTORS(GL32.GL_MAX_FRAGMENT_UNIFORM_VECTORS),
    MAX_FRAMEBUFFER_HEIGHT(GL32.GL_MAX_FRAMEBUFFER_HEIGHT),
    MAX_FRAMEBUFFER_SAMPLES(GL32.GL_MAX_FRAMEBUFFER_SAMPLES),
    MAX_FRAMEBUFFER_WIDTH(GL32.GL_MAX_FRAMEBUFFER_WIDTH),
    MAX_INTEGER_SAMPLES(GL32.GL_MAX_INTEGER_SAMPLES),
    MAX_PROGRAM_TEXEL_OFFSET(GL32.GL_MAX_PROGRAM_TEXEL_OFFSET),
    MAX_RENDERBUFFER_SIZE(GL32.GL_MAX_RENDERBUFFER_SIZE),
    MAX_SAMPLE_MASK_WORDS(GL32.GL_MAX_SAMPLE_MASK_WORDS),
    MAX_SAMPLES(GL32.GL_MAX_SAMPLES),
    MAX_SERVER_WAIT_TIMEOUT(GL32.GL_MAX_SERVER_WAIT_TIMEOUT),
    MAX_SHADER_STORAGE_BLOCK_SIZE(GL32.GL_MAX_SHADER_STORAGE_BLOCK_SIZE),
    MAX_SHADER_STORAGE_BUFFER_BINDINGS(GL32.GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS),
    MAX_TEXTURE_IMAGE_UNITS(GL32.GL_MAX_TEXTURE_IMAGE_UNITS),
    MAX_TEXTURE_LOD_BIAS(GL32.GL_MAX_TEXTURE_LOD_BIAS),
    MAX_TEXTURE_SIZE(GL32.GL_MAX_TEXTURE_SIZE),
    MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS(GL32.GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS),
    MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS(GL32.GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS),
    MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS(GL32.GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS),
    MAX_UNIFORM_BLOCK_SIZE(GL32.GL_MAX_UNIFORM_BLOCK_SIZE),
    MAX_UNIFORM_BUFFER_BINDINGS(GL32.GL_MAX_UNIFORM_BUFFER_BINDINGS),
    MAX_UNIFORM_LOCATIONS(GL32.GL_MAX_UNIFORM_LOCATIONS),
    MAX_VARYING_COMPONENTS(GL32.GL_MAX_VARYING_COMPONENTS),
    MAX_VARYING_VECTORS(GL32.GL_MAX_VARYING_VECTORS),
    MAX_VERTEX_ATOMIC_COUNTERS(GL32.GL_MAX_VERTEX_ATOMIC_COUNTERS),
    MAX_VERTEX_ATTRIB_BINDINGS(GL32.GL_MAX_VERTEX_ATTRIB_BINDINGS),
    MAX_VERTEX_ATTRIB_RELATIVE_OFFSET(GL32.GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET),
    MAX_VERTEX_ATTRIBS(GL32.GL_MAX_VERTEX_ATTRIBS),
    MAX_VERTEX_SHADER_STORAGE_BLOCKS(GL32.GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS),
    MAX_VERTEX_TEXTURE_IMAGE_UNITS(GL32.GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS),
    MAX_VERTEX_OUTPUT_COMPONENTS(GL32.GL_MAX_VERTEX_OUTPUT_COMPONENTS),
    MAX_VERTEX_UNIFORM_BLOCKS(GL32.GL_MAX_VERTEX_UNIFORM_BLOCKS),
    MAX_VERTEX_UNIFORM_COMPONENTS(GL32.GL_MAX_VERTEX_UNIFORM_COMPONENTS),
    MAX_VERTEX_UNIFORM_VECTORS(GL32.GL_MAX_VERTEX_UNIFORM_VECTORS),
    MAX_VIEWPORT_DIMS(GL32.GL_MAX_VIEWPORT_DIMS, 2, Integer.class),
    MIN_PROGRAM_TEXEL_OFFSET(GL32.GL_MIN_PROGRAM_TEXEL_OFFSET),
    MINOR_VERSION(GL32.GL_MINOR_VERSION),
    NUM_COMPRESSED_TEXTURE_FORMATS(GL32.GL_NUM_COMPRESSED_TEXTURE_FORMATS),
    NUM_EXTENSIONS(GL32.GL_NUM_EXTENSIONS),
    NUM_PROGRAM_BINARY_FORMATS(GL32.GL_NUM_PROGRAM_BINARY_FORMATS),
    NUM_SHADER_BINARY_FORMATS(GL32.GL_NUM_SHADER_BINARY_FORMATS),
    PACK_ALIGNMENT(GL32.GL_PACK_ALIGNMENT),
    PACK_ROW_LENGTH(GL32.GL_PACK_ROW_LENGTH),
    PACK_SKIP_PIXELS(GL32.GL_PACK_SKIP_PIXELS),
    PACK_SKIP_ROWS(GL32.GL_PACK_SKIP_ROWS),
    PIXEL_PACK_BUFFER_BINDING(GL32.GL_PIXEL_PACK_BUFFER_BINDING),
    PIXEL_UNPACK_BUFFER_BINDING(GL32.GL_PIXEL_UNPACK_BUFFER_BINDING),
    POLYGON_OFFSET_FACTOR(GL32.GL_POLYGON_OFFSET_FACTOR),
    POLYGON_OFFSET_FILL(GL32.GL_POLYGON_OFFSET_FILL, Boolean.class),
    POLYGON_OFFSET_UNITS(GL32.GL_POLYGON_OFFSET_UNITS),
    PRIMITIVE_RESTART_FIXED_INDEX(GL32.GL_PRIMITIVE_RESTART_FIXED_INDEX, Boolean.class),
    PROGRAM_BINARY_FORMATS(GL32.GL_PROGRAM_BINARY_FORMATS),
    PROGRAM_PIPELINE_BINDING(GL32.GL_PROGRAM_PIPELINE_BINDING),
    RASTERIZER_DISCARD(GL32.GL_RASTERIZER_DISCARD, Boolean.class),
    READ_BUFFER(GL32.GL_READ_BUFFER),
    READ_FRAMEBUFFER_BINDING(GL32.GL_READ_FRAMEBUFFER_BINDING),
    RED_BITS(GL32.GL_RED_BITS),
    RENDERBUFFER_BINDING(GL32.GL_RENDERBUFFER_BINDING),
    SAMPLE_ALPHA_TO_COVERAGE(GL32.GL_SAMPLE_ALPHA_TO_COVERAGE, Boolean.class),
    SAMPLE_BUFFERS(GL32.GL_SAMPLE_BUFFERS),
    SAMPLE_COVERAGE(GL32.GL_SAMPLE_COVERAGE, Boolean.class),
    SAMPLE_COVERAGE_INVERT(GL32.GL_SAMPLE_COVERAGE_INVERT, Boolean.class),
    SAMPLE_COVERAGE_VALUE(GL32.GL_SAMPLE_COVERAGE_VALUE),
    SAMPLER_BINDING(GL32.GL_SAMPLER_BINDING),
    SAMPLES(GL32.GL_SAMPLES),
    SCISSOR_BOX(GL32.GL_SCISSOR_BOX, 4, Integer.class),
    SCISSOR_TEST(GL32.GL_SCISSOR_TEST, Boolean.class),
    SHADER_BINARY_FORMATS(GL32.GL_SHADER_BINARY_FORMATS),
    SHADER_COMPILER(GL32.GL_SHADER_COMPILER, Boolean.class),
    SHADER_STORAGE_BUFFER_BINDING(GL32.GL_SHADER_STORAGE_BUFFER_BINDING),
    SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT(GL32.GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT),
    SHADER_STORAGE_BUFFER_SIZE(GL32.GL_SHADER_STORAGE_BUFFER_SIZE),
    SHADER_STORAGE_BUFFER_START(GL32.GL_SHADER_STORAGE_BUFFER_START),
    STENCIL_BACK_FAIL(GL32.GL_STENCIL_BACK_FAIL),
    STENCIL_BACK_FUNC(GL32.GL_STENCIL_BACK_FUNC),
    STENCIL_BACK_PASS_DEPTH_FAIL(GL32.GL_STENCIL_BACK_PASS_DEPTH_FAIL),
    STENCIL_BACK_PASS_DEPTH_PASS(GL32.GL_STENCIL_BACK_PASS_DEPTH_PASS),
    STENCIL_BACK_REF(GL32.GL_STENCIL_BACK_REF),
    STENCIL_BACK_VALUE_MASK(GL32.GL_STENCIL_BACK_VALUE_MASK),
    STENCIL_BACK_WRITEMASK(GL32.GL_STENCIL_BACK_WRITEMASK),
    STENCIL_BITS(GL32.GL_STENCIL_BITS),
    STENCIL_CLEAR_VALUE(GL32.GL_STENCIL_CLEAR_VALUE),
    STENCIL_FAIL(GL32.GL_STENCIL_FAIL),
    STENCIL_FUNC(GL32.GL_STENCIL_FUNC),
    STENCIL_PASS_DEPTH_FAIL(GL32.GL_STENCIL_PASS_DEPTH_FAIL),
    STENCIL_PASS_DEPTH_PASS(GL32.GL_STENCIL_PASS_DEPTH_PASS),
    STENCIL_REF(GL32.GL_STENCIL_REF),
    STENCIL_TEST(GL32.GL_STENCIL_TEST, Boolean.class),
    STENCIL_VALUE_MASK(GL32.GL_STENCIL_VALUE_MASK),
    STENCIL_WRITEMASK(GL32.GL_STENCIL_WRITEMASK),
    SUBPIXEL_BITS(GL32.GL_SUBPIXEL_BITS),
    TEXTURE_BINDING_2D(GL32.GL_TEXTURE_BINDING_2D),
    TEXTURE_BINDING_2D_ARRAY(GL32.GL_TEXTURE_BINDING_2D_ARRAY),
    TEXTURE_BINDING_3D(GL32.GL_TEXTURE_BINDING_3D),
    TEXTURE_BINDING_CUBE_MAP(GL32.GL_TEXTURE_BINDING_CUBE_MAP),
    TEXTURE_BINDING_2D_MULTISAMPLE(GL32.GL_TEXTURE_BINDING_2D_MULTISAMPLE),
    TRANSFORM_FEEDBACK_BINDING(GL32.GL_TRANSFORM_FEEDBACK_BINDING),
    TRANSFORM_FEEDBACK_ACTIVE(GL32.GL_TRANSFORM_FEEDBACK_ACTIVE, Boolean.class),
    TRANSFORM_FEEDBACK_BUFFER_BINDING(GL32.GL_TRANSFORM_FEEDBACK_BUFFER_BINDING),
    TRANSFORM_FEEDBACK_PAUSED(GL32.GL_TRANSFORM_FEEDBACK_PAUSED, Boolean.class),
    TRANSFORM_FEEDBACK_BUFFER_SIZE(GL32.GL_TRANSFORM_FEEDBACK_BUFFER_SIZE),
    TRANSFORM_FEEDBACK_BUFFER_START(GL32.GL_TRANSFORM_FEEDBACK_BUFFER_START),
    UNIFORM_BUFFER_BINDING(GL32.GL_UNIFORM_BUFFER_BINDING),
    UNIFORM_BUFFER_OFFSET_ALIGNMENT(GL32.GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT),
    UNIFORM_BUFFER_SIZE(GL32.GL_UNIFORM_BUFFER_SIZE),
    UNIFORM_BUFFER_START(GL32.GL_UNIFORM_BUFFER_START),
    UNPACK_ALIGNMENT(GL32.GL_UNPACK_ALIGNMENT),
    UNPACK_IMAGE_HEIGHT(GL32.GL_UNPACK_IMAGE_HEIGHT),
    UNPACK_ROW_LENGTH(GL32.GL_UNPACK_ROW_LENGTH),
    UNPACK_SKIP_IMAGES(GL32.GL_UNPACK_SKIP_IMAGES),
    UNPACK_SKIP_PIXELS(GL32.GL_UNPACK_SKIP_PIXELS),
    UNPACK_SKIP_ROWS(GL32.GL_UNPACK_SKIP_ROWS),
    VERTEX_ARRAY_BINDING(GL32.GL_VERTEX_ARRAY_BINDING),
    VERTEX_BINDING_DIVISOR(GL32.GL_VERTEX_BINDING_DIVISOR),
    VERTEX_BINDING_OFFSET(GL32.GL_VERTEX_BINDING_OFFSET),
    VERTEX_BINDING_STRIDE(GL32.GL_VERTEX_BINDING_STRIDE),
    VIEWPORT(GL32.GL_VIEWPORT, 4, Integer.class);

    public int GL;
    public int n;
    public Class<?> type;
    
    private static Map<Integer, StateParameter> glMap = new HashMap<Integer, StateParameter>();
    
    static {
        for(StateParameter t : StateParameter.values()) {
            glMap.put(t.GL, t);
        }
    }

    private StateParameter(int GL) {
        this.GL = GL;
        this.n = 1;
        this.type = Float.class;
    }
    
    private StateParameter(int GL, int n) {
        this.GL = GL;
        this.n = n;
        this.type = Float.class;
    }

    private StateParameter(int GL, Class<?> type) {
        this.GL = GL;
        this.n = 1;
        this.type = type;
    }

    private StateParameter(int GL, int n, Class<?> type) {
        this.GL = GL;
        this.n = n;
        this.type = type;
    }

    public static StateParameter valueOf(int GL) {
        return glMap.get(GL);
    }
}
