package nl.rumfumme.gl.enums;

import java.util.HashMap;
import java.util.Map;

import com.badlogic.gdx.graphics.GL32;

public enum Type {
    BOOL(GL32.GL_BOOL),
    BOOL_VEC2(GL32.GL_BOOL_VEC2),
    BOOL_VEC3(GL32.GL_BOOL_VEC3),
    BOOL_VEC4(GL32.GL_BOOL_VEC4),
    BYTE(GL32.GL_BYTE),
    UNSIGNED_BYTE(GL32.GL_UNSIGNED_BYTE),
    SHORT(GL32.GL_SHORT),
    UNSIGNED_SHORT(GL32.GL_UNSIGNED_SHORT),
    UNSIGNED_SHORT_4_4_4_4(GL32.GL_UNSIGNED_SHORT_4_4_4_4),
    UNSIGNED_SHORT_5_5_5_1(GL32.GL_UNSIGNED_SHORT_5_5_5_1),
    UNSIGNED_SHORT_5_6_5(GL32.GL_UNSIGNED_SHORT_5_6_5),
    FIXED(GL32.GL_FIXED),
    HALF_FLOAT(GL32.GL_HALF_FLOAT),
    FLOAT(GL32.GL_FLOAT),
    FLOAT_VEC2(GL32.GL_FLOAT_VEC2),
    FLOAT_VEC3(GL32.GL_FLOAT_VEC3),
    FLOAT_VEC4(GL32.GL_FLOAT_VEC4),
    FLOAT_MAT2(GL32.GL_FLOAT_MAT2),
    FLOAT_MAT3(GL32.GL_FLOAT_MAT3),
    FLOAT_MAT4(GL32.GL_FLOAT_MAT4),
    FLOAT_MAT2x3(GL32.GL_FLOAT_MAT2x3),
    FLOAT_MAT2x4(GL32.GL_FLOAT_MAT2x4),
    FLOAT_MAT3x2(GL32.GL_FLOAT_MAT3x2),
    FLOAT_MAT3x4(GL32.GL_FLOAT_MAT3x4),
    FLOAT_MAT4x2(GL32.GL_FLOAT_MAT4x2),
    FLOAT_MAT4x3(GL32.GL_FLOAT_MAT4x3),
    FLOAT_32_UNSIGNED_INT_24_8_REV(GL32.GL_FLOAT_32_UNSIGNED_INT_24_8_REV),
    INT(GL32.GL_INT),
    INT_VEC2(GL32.GL_INT_VEC2),
    INT_VEC3(GL32.GL_INT_VEC3),
    INT_VEC4(GL32.GL_INT_VEC4),
    INT_2_10_10_10_REV(GL32.GL_INT_2_10_10_10_REV),
    UNSIGNED_INT(GL32.GL_UNSIGNED_INT),
    UNSIGNED_INT_VEC2(GL32.GL_UNSIGNED_INT_VEC2),
    UNSIGNED_INT_VEC3(GL32.GL_UNSIGNED_INT_VEC3),
    UNSIGNED_INT_VEC4(GL32.GL_UNSIGNED_INT_VEC4),
    UNSIGNED_INT_10F_11F_11F_REV(GL32.GL_UNSIGNED_INT_10F_11F_11F_REV),
    UNSIGNED_INT_24_8(GL32.GL_UNSIGNED_INT_24_8),
    UNSIGNED_INT_2_10_10_10_REV(GL32.GL_UNSIGNED_INT_2_10_10_10_REV),
    UNSIGNED_INT_5_9_9_9_REV(GL32.GL_UNSIGNED_INT_5_9_9_9_REV),
    SAMPLER_2D(GL32.GL_SAMPLER_2D),
    SAMPLER_3D(GL32.GL_SAMPLER_3D),
    SAMPLER_CUBE(GL32.GL_SAMPLER_CUBE),
    SAMPLER_2D_SHADOW(GL32.GL_SAMPLER_2D_SHADOW),
    SAMPLER_2D_ARRAY(GL32.GL_SAMPLER_2D_ARRAY),
    SAMPLER_2D_ARRAY_SHADOW(GL32.GL_SAMPLER_2D_ARRAY_SHADOW),
    SAMPLER_2D_MULTISAMPLE(GL32.GL_SAMPLER_2D_MULTISAMPLE),
    SAMPLER_2D_MULTISAMPLE_ARRAY(GL32.GL_SAMPLER_2D_MULTISAMPLE_ARRAY),
    SAMPLER_CUBE_SHADOW(GL32.GL_SAMPLER_CUBE_SHADOW),
    SAMPLER_CUBE_MAP_ARRAY(GL32.GL_SAMPLER_CUBE_MAP_ARRAY),
    SAMPLER_CUBE_MAP_ARRAY_SHADOW(GL32.GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW),
    SAMPLER_BUFFER(GL32.GL_SAMPLER_BUFFER),
    INT_SAMPLER_2D(GL32.GL_INT_SAMPLER_2D),
    INT_SAMPLER_3D(GL32.GL_INT_SAMPLER_3D),
    INT_SAMPLER_CUBE(GL32.GL_INT_SAMPLER_CUBE),
    INT_SAMPLER_2D_ARRAY(GL32.GL_INT_SAMPLER_2D_ARRAY),
    INT_SAMPLER_2D_MULTISAMPLE(GL32.GL_INT_SAMPLER_2D_MULTISAMPLE),
    INT_SAMPLER_2D_MULTISAMPLE_ARRAY(GL32.GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY),
    INT_SAMPLER_CUBE_MAP_ARRAY(GL32.GL_INT_SAMPLER_CUBE_MAP_ARRAY),
    INT_SAMPLER_BUFFER(GL32.GL_INT_SAMPLER_BUFFER),
    UNSIGNED_INT_SAMPLER_2D(GL32.GL_UNSIGNED_INT_SAMPLER_2D),
    UNSIGNED_INT_SAMPLER_3D(GL32.GL_UNSIGNED_INT_SAMPLER_3D),
    UNSIGNED_INT_SAMPLER_CUBE(GL32.GL_UNSIGNED_INT_SAMPLER_CUBE),
    UNSIGNED_INT_SAMPLER_2D_ARRAY(GL32.GL_UNSIGNED_INT_SAMPLER_2D_ARRAY),
    UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE(GL32.GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE),
    UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY(GL32.GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY),
    UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY(GL32.GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY),
    UNSIGNED_INT_SAMPLER_BUFFER(GL32.GL_UNSIGNED_INT_SAMPLER_BUFFER),
    IMAGE_2D(GL32.GL_IMAGE_2D),
    IMAGE_3D(GL32.GL_IMAGE_3D),
    IMAGE_CUBE(GL32.GL_IMAGE_CUBE),
    IMAGE_2D_ARRAY(GL32.GL_IMAGE_2D_ARRAY),
    IMAGE_CUBE_MAP_ARRAY(GL32.GL_IMAGE_CUBE_MAP_ARRAY),
    IMAGE_BUFFER(GL32.GL_IMAGE_BUFFER),
    INT_IMAGE_2D(GL32.GL_INT_IMAGE_2D),
    INT_IMAGE_3D(GL32.GL_INT_IMAGE_3D),
    INT_IMAGE_CUBE(GL32.GL_INT_IMAGE_CUBE),
    INT_IMAGE_2D_ARRAY(GL32.GL_INT_IMAGE_2D_ARRAY),
    INT_IMAGE_CUBE_MAP_ARRAY(GL32.GL_INT_IMAGE_CUBE_MAP_ARRAY),
    INT_IMAGE_BUFFER(GL32.GL_INT_IMAGE_BUFFER),
    UNSIGNED_INT_IMAGE_2D(GL32.GL_UNSIGNED_INT_IMAGE_2D),
    UNSIGNED_INT_IMAGE_3D(GL32.GL_UNSIGNED_INT_IMAGE_3D),
    UNSIGNED_INT_IMAGE_CUBE(GL32.GL_UNSIGNED_INT_IMAGE_CUBE),
    UNSIGNED_INT_IMAGE_2D_ARRAY(GL32.GL_UNSIGNED_INT_IMAGE_2D_ARRAY),
    UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY(GL32.GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY),
    UNSIGNED_INT_IMAGE_BUFFER(GL32.GL_UNSIGNED_INT_IMAGE_BUFFER),
    UNSIGNED_INT_ATOMIC_COUNTER(GL32.GL_UNSIGNED_INT_ATOMIC_COUNTER);
    
    public int GL;
    private static Map<Integer, Type> glMap = new HashMap<Integer, Type>();
    
    static {
        for(Type t : Type.values()) {
            glMap.put(t.GL, t);
        }
    }

    private Type(int GL) {
        this.GL = GL;
    }
    
    public static Type valueOf(int GL) {
        return glMap.get(GL);
    }
}
